# Generated by Django 4.2 on 2023-06-06 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_alter_user_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('option1', models.CharField(max_length=80)),
                ('option2', models.CharField(max_length=80)),
                ('option3', models.CharField(max_length=80)),
                ('option1_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
