# Generated by Django 4.2 on 2023-06-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_polling_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='polling',
            name='option2_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='polling',
            name='option3_count',
            field=models.IntegerField(default=0),
        ),
    ]
