# Generated by Django 4.2 on 2023-06-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_polling_option2_count_polling_option3_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='polling',
            name='choice_count',
            field=models.IntegerField(default=0),
        ),
    ]
