# Generated by Django 4.2 on 2023-06-09 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll', '0009_polling_user_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polling',
            name='user_count',
        ),
        migrations.AddField(
            model_name='polling',
            name='voters',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
