# Generated by Django 4.2 on 2023-06-09 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0010_remove_polling_user_count_polling_voters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polling',
            name='choice_count',
        ),
    ]
